### ISSUE TITLE
So no more RSS ?

### ISSUE THREAD

**Issue by RealZogzog** [C-D-Lewis/blog#1]
Hello, I was kept informed about new articles by your RSS flux.
I like your posts, but I won't visit your blog every day......

**Comment by C-D-Lewis** [comment]
Hi, thanks for reading! I had forgotten about the feed in all honesty. I think every blog deserves an RSS feed, so I'll look into adding one soon.

**Comment by C-D-Lewis** [comment]
@RealZogzog I've added a feed and button (valid by W3C validator). Please let me know if it works for you.

**Comment by RealZogzog** [comment]
Yes, It's working fine.
Thank you.

P.S. I find your work awesome and very helpful, keep up the good work.

**Comment by C-D-Lewis** [comment]
@RealZogzog Thanks! Hopefully more posts now the new site is finished 🙂
